[package]
name = "simple_ea"
version = "0.1.0"
authors = ["Dr. Shahin Rostami"]
description = "Simple Multi-Objective Evolutionary Algorithm (MOEA) implemented in the Rust programming language."
license = "MIT"
repository = "https://github.com/shahinrostami/simple_ea"


[dependencies]
rand = "0.3"